# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrewkc/Codes/compilers-project-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrewkc/Codes/compilers-project-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrewkc/Codes/compilers-project-1/CMakeFiles /home/andrewkc/Codes/compilers-project-1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrewkc/Codes/compilers-project-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imp

# Build rule for target.
imp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imp
.PHONY : imp

# fast build rule for target.
imp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/build
.PHONY : imp/fast

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

#=============================================================================
# Target rules for targets named svm

# Build rule for target.
svm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 svm
.PHONY : svm

# fast build rule for target.
svm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/build
.PHONY : svm/fast

imp_ast.o: imp_ast.cpp.o
.PHONY : imp_ast.o

# target to build an object file
imp_ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/imp_ast.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_ast.cpp.o
.PHONY : imp_ast.cpp.o

imp_ast.i: imp_ast.cpp.i
.PHONY : imp_ast.i

# target to preprocess a source file
imp_ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/imp_ast.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_ast.cpp.i
.PHONY : imp_ast.cpp.i

imp_ast.s: imp_ast.cpp.s
.PHONY : imp_ast.s

# target to generate assembly for a file
imp_ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/imp_ast.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_ast.cpp.s
.PHONY : imp_ast.cpp.s

imp_compiler.o: imp_compiler.cpp.o
.PHONY : imp_compiler.o

# target to build an object file
imp_compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_compiler.cpp.o
.PHONY : imp_compiler.cpp.o

imp_compiler.i: imp_compiler.cpp.i
.PHONY : imp_compiler.i

# target to preprocess a source file
imp_compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_compiler.cpp.i
.PHONY : imp_compiler.cpp.i

imp_compiler.s: imp_compiler.cpp.s
.PHONY : imp_compiler.s

# target to generate assembly for a file
imp_compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_compiler.cpp.s
.PHONY : imp_compiler.cpp.s

imp_parser.o: imp_parser.cpp.o
.PHONY : imp_parser.o

# target to build an object file
imp_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/imp_parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_parser.cpp.o
.PHONY : imp_parser.cpp.o

imp_parser.i: imp_parser.cpp.i
.PHONY : imp_parser.i

# target to preprocess a source file
imp_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/imp_parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_parser.cpp.i
.PHONY : imp_parser.cpp.i

imp_parser.s: imp_parser.cpp.s
.PHONY : imp_parser.s

# target to generate assembly for a file
imp_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/imp_parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/imp_parser.cpp.s
.PHONY : imp_parser.cpp.s

svm_ast.o: svm_ast.cpp.o
.PHONY : svm_ast.o

# target to build an object file
svm_ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_ast.cpp.o
.PHONY : svm_ast.cpp.o

svm_ast.i: svm_ast.cpp.i
.PHONY : svm_ast.i

# target to preprocess a source file
svm_ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_ast.cpp.i
.PHONY : svm_ast.cpp.i

svm_ast.s: svm_ast.cpp.s
.PHONY : svm_ast.s

# target to generate assembly for a file
svm_ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_ast.cpp.s
.PHONY : svm_ast.cpp.s

svm_parser.o: svm_parser.cpp.o
.PHONY : svm_parser.o

# target to build an object file
svm_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_parser.cpp.o
.PHONY : svm_parser.cpp.o

svm_parser.i: svm_parser.cpp.i
.PHONY : svm_parser.i

# target to preprocess a source file
svm_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_parser.cpp.i
.PHONY : svm_parser.cpp.i

svm_parser.s: svm_parser.cpp.s
.PHONY : svm_parser.s

# target to generate assembly for a file
svm_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_parser.cpp.s
.PHONY : svm_parser.cpp.s

svm_run.o: svm_run.cpp.o
.PHONY : svm_run.o

# target to build an object file
svm_run.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_run.cpp.o
.PHONY : svm_run.cpp.o

svm_run.i: svm_run.cpp.i
.PHONY : svm_run.i

# target to preprocess a source file
svm_run.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_run.cpp.i
.PHONY : svm_run.cpp.i

svm_run.s: svm_run.cpp.s
.PHONY : svm_run.s

# target to generate assembly for a file
svm_run.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svm.dir/build.make CMakeFiles/svm.dir/svm_run.cpp.s
.PHONY : svm_run.cpp.s

tests/imp_test.o: tests/imp_test.cpp.o
.PHONY : tests/imp_test.o

# target to build an object file
tests/imp_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/tests/imp_test.cpp.o
.PHONY : tests/imp_test.cpp.o

tests/imp_test.i: tests/imp_test.cpp.i
.PHONY : tests/imp_test.i

# target to preprocess a source file
tests/imp_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/tests/imp_test.cpp.i
.PHONY : tests/imp_test.cpp.i

tests/imp_test.s: tests/imp_test.cpp.s
.PHONY : tests/imp_test.s

# target to generate assembly for a file
tests/imp_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/tests/imp_test.cpp.s
.PHONY : tests/imp_test.cpp.s

utils/imp_value.o: utils/imp_value.cpp.o
.PHONY : utils/imp_value.o

# target to build an object file
utils/imp_value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/utils/imp_value.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/utils/imp_value.cpp.o
.PHONY : utils/imp_value.cpp.o

utils/imp_value.i: utils/imp_value.cpp.i
.PHONY : utils/imp_value.i

# target to preprocess a source file
utils/imp_value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/utils/imp_value.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/utils/imp_value.cpp.i
.PHONY : utils/imp_value.cpp.i

utils/imp_value.s: utils/imp_value.cpp.s
.PHONY : utils/imp_value.s

# target to generate assembly for a file
utils/imp_value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/utils/imp_value.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/utils/imp_value.cpp.s
.PHONY : utils/imp_value.cpp.s

visitors/imp_codegenerator.o: visitors/imp_codegenerator.cpp.o
.PHONY : visitors/imp_codegenerator.o

# target to build an object file
visitors/imp_codegenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_codegenerator.cpp.o
.PHONY : visitors/imp_codegenerator.cpp.o

visitors/imp_codegenerator.i: visitors/imp_codegenerator.cpp.i
.PHONY : visitors/imp_codegenerator.i

# target to preprocess a source file
visitors/imp_codegenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_codegenerator.cpp.i
.PHONY : visitors/imp_codegenerator.cpp.i

visitors/imp_codegenerator.s: visitors/imp_codegenerator.cpp.s
.PHONY : visitors/imp_codegenerator.s

# target to generate assembly for a file
visitors/imp_codegenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_codegenerator.cpp.s
.PHONY : visitors/imp_codegenerator.cpp.s

visitors/imp_interpreter.o: visitors/imp_interpreter.cpp.o
.PHONY : visitors/imp_interpreter.o

# target to build an object file
visitors/imp_interpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/visitors/imp_interpreter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_interpreter.cpp.o
.PHONY : visitors/imp_interpreter.cpp.o

visitors/imp_interpreter.i: visitors/imp_interpreter.cpp.i
.PHONY : visitors/imp_interpreter.i

# target to preprocess a source file
visitors/imp_interpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/visitors/imp_interpreter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_interpreter.cpp.i
.PHONY : visitors/imp_interpreter.cpp.i

visitors/imp_interpreter.s: visitors/imp_interpreter.cpp.s
.PHONY : visitors/imp_interpreter.s

# target to generate assembly for a file
visitors/imp_interpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/visitors/imp_interpreter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_interpreter.cpp.s
.PHONY : visitors/imp_interpreter.cpp.s

visitors/imp_printer.o: visitors/imp_printer.cpp.o
.PHONY : visitors/imp_printer.o

# target to build an object file
visitors/imp_printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/visitors/imp_printer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_printer.cpp.o
.PHONY : visitors/imp_printer.cpp.o

visitors/imp_printer.i: visitors/imp_printer.cpp.i
.PHONY : visitors/imp_printer.i

# target to preprocess a source file
visitors/imp_printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/visitors/imp_printer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_printer.cpp.i
.PHONY : visitors/imp_printer.cpp.i

visitors/imp_printer.s: visitors/imp_printer.cpp.s
.PHONY : visitors/imp_printer.s

# target to generate assembly for a file
visitors/imp_printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imp.dir/build.make CMakeFiles/imp.dir/visitors/imp_printer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_printer.cpp.s
.PHONY : visitors/imp_printer.cpp.s

visitors/imp_typechecker.o: visitors/imp_typechecker.cpp.o
.PHONY : visitors/imp_typechecker.o

# target to build an object file
visitors/imp_typechecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_typechecker.cpp.o
.PHONY : visitors/imp_typechecker.cpp.o

visitors/imp_typechecker.i: visitors/imp_typechecker.cpp.i
.PHONY : visitors/imp_typechecker.i

# target to preprocess a source file
visitors/imp_typechecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_typechecker.cpp.i
.PHONY : visitors/imp_typechecker.cpp.i

visitors/imp_typechecker.s: visitors/imp_typechecker.cpp.s
.PHONY : visitors/imp_typechecker.s

# target to generate assembly for a file
visitors/imp_typechecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/visitors/imp_typechecker.cpp.s
.PHONY : visitors/imp_typechecker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compiler"
	@echo "... imp"
	@echo "... svm"
	@echo "... imp_ast.o"
	@echo "... imp_ast.i"
	@echo "... imp_ast.s"
	@echo "... imp_compiler.o"
	@echo "... imp_compiler.i"
	@echo "... imp_compiler.s"
	@echo "... imp_parser.o"
	@echo "... imp_parser.i"
	@echo "... imp_parser.s"
	@echo "... svm_ast.o"
	@echo "... svm_ast.i"
	@echo "... svm_ast.s"
	@echo "... svm_parser.o"
	@echo "... svm_parser.i"
	@echo "... svm_parser.s"
	@echo "... svm_run.o"
	@echo "... svm_run.i"
	@echo "... svm_run.s"
	@echo "... tests/imp_test.o"
	@echo "... tests/imp_test.i"
	@echo "... tests/imp_test.s"
	@echo "... utils/imp_value.o"
	@echo "... utils/imp_value.i"
	@echo "... utils/imp_value.s"
	@echo "... visitors/imp_codegenerator.o"
	@echo "... visitors/imp_codegenerator.i"
	@echo "... visitors/imp_codegenerator.s"
	@echo "... visitors/imp_interpreter.o"
	@echo "... visitors/imp_interpreter.i"
	@echo "... visitors/imp_interpreter.s"
	@echo "... visitors/imp_printer.o"
	@echo "... visitors/imp_printer.i"
	@echo "... visitors/imp_printer.s"
	@echo "... visitors/imp_typechecker.o"
	@echo "... visitors/imp_typechecker.i"
	@echo "... visitors/imp_typechecker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

